### ISSUE TITLE
The color disappear when activating the hud

### ISSUE THREAD

**Issue by bobongski** [danielmj/DJProgressHUD_OSX#3]
The color disappear when activating the hud you need to resize the window in order to retrieve color.
![screen shot 2015-06-05 at 9 17 29 am](https://cloud.githubusercontent.com/assets/3972630/7997690/c4aae8d4-0b63-11e5-849d-ce91843a303a.png)
![screen shot 2015-06-05 at 9 17 42 am](https://cloud.githubusercontent.com/assets/3972630/7997691/cf2e46de-0b63-11e5-9515-f81124a9995e.png)
![screen shot 2015-06-05 at 9 13 16 am](https://cloud.githubusercontent.com/assets/3972630/7997695/db58503a-0b63-11e5-9931-26241c1afdee.png)

**Comment by danielmj** [comment]
Currently you can only change the color of instantiated progress indicators. In order to display the progress as a HUD, you have to use the class methods. In this way you cannot set the color of the HUD.

I hadn't designed the HUD to change colors. I can look into this as a possible option in the future.
